### ISSUE TITLE
request for including statsd plugin 

### ISSUE THREAD

**Issue by sandys** [conda-forge/uwsgi-feedstock#15]
Issue:
Statsd is the most popular tool for reporting metrics from uwsgi. The plugin is optionally built in uwsgi by using a build flag "UWSGI_EMBED_PLUGINS=stats_pusher_statsd" while doing pip install. However, uwsgi builds have a lot of issues in linux (e.g. https://github.com/unbit/uwsgi/issues/1516). It would be a huge help if conda could include this.

in fact, the common advice given when installing uwsgi inside anaconda installation is to NOT build it and use the provided conda package. https://github.com/unbit/uwsgi/issues/1770

**Comment by sandys** [comment]
you're awesome! 
thank you so much.

**Comment by ocefpaf** [comment]
I'm not a user of `uwsgi` so I did not add a test for the plugin b/c I have no idea how it is supposed to work. If you can come up with a quick and simple test please let me know.

**Comment by sandys** [comment]
hi,
I dont know how to format it for conda-forge, but its pretty simple conceptually

```
~/Code/miniconda3/bin/uwsgi --plugin-list                                                                                                  git:(apiv5) ✗ 

*** uWSGI loaded generic plugins ***
gevent
nagios
rrdtool
carbon
corerouter
fastrouter
http
ugreen
syslog
rsyslog
logsocket
router_uwsgi
router_redirect
router_basicauth
zergpool
redislog
mongodblog
router_rewrite
router_http
logfile
router_cache
rawrouter
router_static
sslrouter
cheaper_busyness
transformation_tofile
transformation_gzip
transformation_chunked
transformation_offload
router_memcached
router_redis
router_hash
router_expires
router_metrics
transformation_template
stats_pusher_socket

*** uWSGI loaded request plugins ***
0: python
17: spooler
18: symcall
100: ping
110: signal
111: cache
173: rpc
--- end of plugins list ---


```

statsd will show up there.

**Comment by ocefpaf** [comment]
Thanks. That works!

**Comment by sandys** [comment]
Btw this is a pretty big deal for a lot of people. It's not a bad idea to
put it on the GitHub readme.

**Comment by ocefpaf** [comment]
Our README is auto-generate and mostly boilerplate stuff :-/
