### ISSUE TITLE
Build for Python 3.6?

### ISSUE THREAD

**Issue by ericmjl** [conda-forge/uwsgi-feedstock#3]
Hi team,

Just wondering if there's plans to update the repository so that uWSGI can be conda-installed in Python 3.6 environments?

Please let me know - though I will mention I'm a maintainer on enough recipes that I'm a bit tired with putting in PRs for other recipes.

Cheers,
Eric

**Comment by toote** [comment]
Version 2.0.15 is not available in Python 3.6 for linux environments because [the CI failed due to it being unable to clone the repository](https://circleci.com/gh/conda-forge/uwsgi-feedstock/44) :(

**Comment by toote** [comment]
And the latest merges made it build correctly again. Thanks a bunch!
