### ISSUE TITLE
uwsgi 2.0.15 requires libicui18n.so.58 that is missing as a conda package

### ISSUE THREAD

**Issue by komailrk** [conda-forge/uwsgi-feedstock#7]
When running uwsgi on Fedora 26:
`uwsgi: error while loading shared libraries: libicui18n.so.58: cannot open shared object file: No such file or directory`

This issue is not seen on uwsgi 2.0.12. Quick workaround is to use this version.

```
bash-4.4$ ldd /opt/conda/bin/uwsgi
        linux-vdso.so.1 (0x00007ffd76b75000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f342411b000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f3423e05000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f3423c01000)
        libz.so.1 => /opt/conda/envs/bin/../lib/libz.so.1 (0x00007f34239eb000)
        libpcre.so.1 => /opt/conda/envs/bin/../lib/libpcre.so.1 (0x00007f34237a8000)
        libyaml-0.so.2 => /opt/conda/envs/bin/../lib/libyaml-0.so.2 (0x00007f3423587000)
        libjansson.so.4 => /opt/conda/envs/bin/../lib/libjansson.so.4 (0x00007f342337b000)
        libssl.so.1.0.0 => /opt/conda/envs/bin/../lib/libssl.so.1.0.0 (0x00007f3423104000)
        libcrypto.so.1.0.0 => /opt/conda/envs/bin/../lib/libcrypto.so.1.0.0 (0x00007f3422ccd000)
        libxml2.so.2 => /opt/conda/envs/bin/../lib/libxml2.so.2 (0x00007f3422972000)
        liblzma.so.5 => /lib64/liblzma.so.5 (0x00007f342274c000)
        libiconv.so.2 => /opt/conda/envs/bin/../lib/libiconv.so.2 (0x00007f342245b000)
        libicui18n.so.58 => not found
        libicuuc.so.58 => not found
        libicudata.so.58 => not found
        libutil.so.1 => /lib64/libutil.so.1 (0x00007f3422258000)
        libpython2.7.so.1.0 => /opt/conda/envs/bin/../lib/libpython2.7.so.1.0 (0x00007f3421e5c000)
        libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007f3421c24000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f3421853000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f3424340000)
        libfreebl3.so => /lib64/libfreebl3.so (0x00007f3421650000)
```

**Comment by ocefpaf** [comment]
Please see https://conda-forge.org/docs/conda-forge_gotchas.html#using-multiple-channels

**Comment by mariusroets** [comment]
> Please see https://conda-forge.org/docs/conda-forge_gotchas.html#using-multiple-channels

That link does not exist, and the comment is not otherwise helpful in determining how to solve this. I'm really struggling to get uwsgi working.

**Comment by ocefpaf** [comment]
> That link does not exist,

You mean: no longer exists b/c you are on a 2017 thread, right :wink: 

Here is the updated one: https://conda-forge.org/docs/user/tipsandtricks.html#how-to-fix-it

> and the comment is not otherwise helpful in determining how to solve this. I'm really struggling to get uwsgi working.

See the docs and, if that does not solve it for you open a new issue so we can debug your case with your debug info.
